In [1]:
import numpy as np

 # Numpy Indexing and Slicing of vectors

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
# indexing
print(arr[6])

17


In [14]:
# slicing
# arr[start:endpoint:]
arr[1:5]
arr[:5] # default start value
arr[:] # auatmatic at last 
arr[3:]
arr_slice = arr[3::2] # arr[start::steps]
arr_slice

array([14, 16, 18, 20])

# Numpy Indexing and Slicing of Vectors

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[5] # rows target -> 0,1,2,3,4,5

array([26, 27, 28, 29, 30])

In [22]:
print(arr[0,0])

1


In [23]:
print(arr[0,4])

5


In [24]:
print(arr[5,4])

30


In [26]:
# slicing
# 2,3
# 7,8
slice = arr[0:2,1:3] # arr[row,col]
slice


array([[2, 3],
       [7, 8]])

In [33]:
arr[3:6,3:6] # or
arr[3:,3:]


array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr[:,2 # created vector

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [36]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
bool_index = arr% 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [38]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])