In [2]:
import numpy as np

# Valid sudoku

In [8]:
s = np.array([
    [5,3,4,6,7,8,9,1,2], # sum = 45
    [6,7,2,1,9,5,3,4,8], 
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    
])

In [12]:
# sum of each and every row -> rows axis -> 0 for column 1
b = np.sum(s,axis=1) # if all values are not equal then we can say sudoku is not valid
# b[b==45]
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [17]:
for i in b:
    if i!=45 :
        print('sudoku is not valid')
        break
else:
    print('for rows it is valid')

for rows it is valid


In [18]:
c = np.sum(s,axis=1)
for i in b:
    if i!=45 :
        print('sudoku is not valid')
        break
else:
     print('for columns it is valid')

for columns it is valid


In [19]:
# s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [20]:
# s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [21]:
# s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [24]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3,j:j+3])
         n = s[i:i+3,j:j+3]
         print(n.sum())

45
45
45
45
45
45
45
45
45


# General Questions

In [25]:
import numpy as np 

In [68]:
# coluns :[Age,Math Marks , Sceince Marks]
data = np.array([
    [18,85,78], # student 1
    [19,92,88], # student 2
    [17,76,95], # student 3
    [18,65,70], # student 4
    [20,90,85], # student 5
])

In [69]:
# get the shape of the matrix
data.shape

(5, 3)

In [70]:
# find the average age of students.
np.mean(data[:,0]) # all rows first column

np.float64(18.4)

In [71]:
# Extract Math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [72]:
# Find the highest Science mark
max(data[:,2])

np.int64(95)

In [73]:
# Get details of the student who scored more than 90 in Math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [74]:
# Increase Math marks of all students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [75]:
# find how many students are younger than 19
len(data[data[:,0] < 19])

3

In [76]:
# calculate the average marks in each subject(column-wise mean).
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [77]:
# Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [78]:
# Replace all Science marks < 75 with 0.
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [79]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])