In [1]:
import numpy as np

# Array Operation


# Arithmetic operation

In [52]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [53]:
a1

array([1, 2, 3, 4, 5])

In [54]:
a2

array([ 6,  7,  8,  9, 10])

In [55]:
a1 + a2  # arrays saize should be same 

array([ 7,  9, 11, 13, 15])

In [56]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [57]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [58]:
a1 / a2 

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [59]:
a1 // a2 # floor division

array([0, 0, 0, 0, 0])

In [60]:
a1**a2 # expontital

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [61]:
l = [10,20,30,40]
arr = np.array(l)

In [62]:
# l + 10 

In [63]:
for i in l:
    print(i+10)

20
30
40
50


In [64]:
# broadcastinga
arr + 10 

array([20, 30, 40, 50])

matrix

In [65]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [67]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# Deep and Shallow copy

In [94]:
# shallow copy -> whenever you are slicing an array vo apna ek alag portion bna lete hai or space bna lete hai ram ke andr to agar aray ke andr kuchh change ho rhe slice me to main array me koi changes nhi hoga
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
slice= a[0:5]
slice

array([1, 2, 3, 4, 5])

In [96]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [97]:
# Deep copy -> agar slice me change kr rhe to amin array me chnges ho rhe ha

In [98]:
a[4:6] * 10 

array([50, 60])

In [99]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

chnage 

In [100]:
# b = a

In [101]:
# b[0] = 99

In [102]:
# b

In [103]:
# a

No changes if use 

In [104]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [105]:
b = a.copy()

In [106]:
b[0] = 99 

In [107]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [108]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix operation

In [112]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [113]:
A

array([[1, 2],
       [3, 4]])

In [114]:
B

array([[5, 6],
       [7, 8]])

In [116]:
# multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [117]:
# multiplication
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [118]:
A

array([[1, 2],
       [3, 4]])

In [119]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manupulation

Stacking Array

* can't stack to matcrix only use vector

In [122]:
A

array([[1, 2],
       [3, 4]])

In [123]:
B

array([[5, 6],
       [7, 8]])

In [125]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [126]:
np.vstack((a,b)) # tuples form ek hi positional argument(v-> vertical)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
np.hstack((a,b)) # h -> horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [129]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [131]:
np.hsplit(c,2) # split in onlu equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [133]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [132]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [135]:
a = np.vsplit(c,4)

In [136]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
